name: baseline_github_action

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
    branches: 
      - development
      - main
      
jobs:
  Linux_Run_Tests:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: "Echo Hello World"
        run:  echo "Hello World Hello"
