# This Action Pubhlishes to NPM Automatically.
on:
  workflow_dispatch:
  push:
    branches: main

jobs:
  publish: # Name
    runs-on: ubuntu-latest
    environment: npm_publishing
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: Run Testing
        run: npm test
        # YOU NEED A BUILD STEP TO POPULATE THE DIST FOLDER!
      - name: Publish to NPM 
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.LAYER8_INTERCEPTOR_MIDDLEWARE_TOKEN }}
          registry: https://registry.npmjs.org
          access: public